# Run before project() so Linux's default build produces the Windows editor.
if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
    set(CMAKE_BUILD_TYPE Release CACHE STRING "Build type" FORCE)
endif()
option(APATH_CORE_ONLY "Build portable core without the Windows UI" OFF)
option(APATH_BUILD_TESTS "Build correctness and Windows integration tests" OFF)
option(APATH_SANITIZE "Enable native address/undefined sanitizers" OFF)
option(APATH_WARNINGS_AS_ERRORS "Treat compiler warnings as errors" OFF)
if(CMAKE_HOST_UNIX AND NOT APATH_CORE_ONLY AND NOT CMAKE_TOOLCHAIN_FILE AND NOT CMAKE_C_COMPILER)
    find_program(APATH_MINGW_CC NAMES x86_64-w64-mingw32-gcc i686-w64-mingw32-gcc)
    if(NOT APATH_MINGW_CC)
        message(FATAL_ERROR "Install MinGW-w64, or supply a MinGW toolchain. For native core only use -DAPATH_CORE_ONLY=ON.")
    endif()
    set(CMAKE_SYSTEM_NAME Windows)
    set(CMAKE_C_COMPILER "${APATH_MINGW_CC}" CACHE FILEPATH "MinGW compiler")
    string(REGEX REPLACE "gcc$" "windres" APATH_MINGW_RC "${APATH_MINGW_CC}")
    set(CMAKE_RC_COMPILER "${APATH_MINGW_RC}" CACHE FILEPATH "MinGW resource compiler")
endif()
